### ISSUE TITLE
Does not work with new projects.

### ISSUE THREAD

**Issue by shawnmclean** [remogloor/Ninject.Web.WebApi#1]
I can't seem to get this to work when setting it up with new projects created on my own. Your sample works fine but it does not find the bindings for constructor injection in the controller when I used all methods you provided in your sample (module, inside webcommon, etc).

Could you provide a new sample that has all the required libraries that is independent from this project?

**Comment by remogloor** [comment]
I just checked that there is no issue with this extension (at least not with the lastest MVC4 preview):
- Create a new MVC4 WEB Api project
- Nuget Install-Package Ninject.Web.WebAPI
- Change controller + add bindings

that way constructor injection works
