### ISSUE TITLE
Can this be used alongside mvc?

### ISSUE THREAD

**Issue by shawnmclean** [remogloor/Ninject.Web.WebApi#2]
My project consists of both mvc and webapi controllers (ApiController and Controller). The Api controllers get injected properly but the normal mvc controllers does not get injected. Is there a way I can do both with ninject?

**Comment by remogloor** [comment]
Use Ninject.MVC3 for MVC

**Comment by shawnmclean** [comment]
Hi, including the NinjectMVC3 in the webapi project still doesn't work. I still get the `No parameterless constructor defined for this object.` The bindings work well for ApiControllers but not the normal ones. Did you try it? When you create a WebApi project, try to do a constructor injection on the HomeController.

**Comment by remogloor** [comment]
Yes this is tested and working with the latest versions on nuget.
